// flow-typed signature: 79f2c4b3b99a19f0e6e0e308c9c0e2fd
// flow-typed version: <<STUB>>/@babel/plugin-proposal-object-rest-spread_v^7.0.0-beta.34/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-object-rest-spread'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-object-rest-spread' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-object-rest-spread/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-object-rest-spread/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-object-rest-spread/lib/index'>;
}
